# Generated by Django 4.2 on 2024-08-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('fecha_emision', models.DateField()),
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.FloatField()),
                ('costo_obra', models.FloatField()),
                ('porcentaje_utilidad', models.FloatField()),
                ('total', models.FloatField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotiza_obras.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_mateiral', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField()),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_productos',
            fields=[
                ('id_detalle_prodcuto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('porcentaje_utilidad', models.FloatField()),
                ('costo_material', models.FloatField()),
                ('precio', models.FloatField()),
                ('valor', models.FloatField()),
                ('costo_total', models.FloatField()),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotiza_obras.cotizacion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotiza_obras.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_mateirales',
            fields=[
                ('id_detalle_material', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_material', models.FloatField()),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('valor', models.FloatField()),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotiza_obras.cotizacion')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotiza_obras.material')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotiza_obras.producto')),
            ],
        ),
    ]
